### ISSUE TITLE
Clang can be a bit difficult to install. 

### ISSUE THREAD

**Issue by WallStProg** [mozafari/vprofiler#18]
>Clang can be a bit difficult to install. 

You're not kidding.  This article (http://btorpey.github.io/blog/2015/01/02/building-clang/) may help.  Comments welcome.

**Comment by jrectorb** [comment]
Could you give some context on what you're having problems with specifically?  Also, yes, agreed.  It's a pretty unpleasant install.

**Comment by sensssz** [comment]
Hello @WallStProg, thanks for the link. I think it will come in handy to other people so I've added it to the wiki :)
